In [393]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split


import pandas as pd
import numpy as np

# Dataset overview

In [394]:
data = pd.read_csv('./Dataset_dumarey/original_csv/tmp.csv')

In [395]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,·2.47174E+18,17/07/202116:46,17/07/202119:26,"2,306,385,938","2,315,879,688",541.0,352.0,trip,NaN
1,·2.47174E+l8,17/07/202119:29,17/07/202120:01,"2,315,879,688","2,315,879,688",NaN,647.0,charge,NaN
2,-2.47174E+18,17/07/202120:01,17/07/202122:36,"2,315,879,688","232,423,125",647.0,478.0,trip,NaN
3,·2.47174E+l8,17/07/202123:05,17/07/2021 23:55,"232,423,125","232,723,125",474.0,419.0,trip,NaN
4,·2.47174E+18,17/07/2021 23:55,18/07/202101:05,"232,723,125","2,327,264,063",419.0,392.0,trip,NaN

In [396]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vin          32 non-null     object
 1   timestamp    32 non-null     object
 2   end_time     32 non-null     object
 3   odo          32 non-null     object
 4   end_odo      32 non-null     object
 5   soc          30 non-null     float64
 6   end_soc      31 non-null     float64
 7   event        32 non-null     object
 8   charge_mode  9 non-null      object
dtypes: float64(2), object(7)
memory usage: 2.4+ KB

# Data Cleaning

In [397]:
def substitute_comma(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", ".")     
    ts = ts.replace(", ", ".")
    ts = ts.replace(" , ", ".")    
    ts = ts.replace(" ,", ".")       
    ts = ts.replace(". ", ".")    
    ts = ts.replace(" .", ".") 
    ts = ts.replace(" . ", ".")       
    return ts 
def remove_comma_odo(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", "")         
    ts = ts.replace(", ", "")        
    ts = ts.replace(" ,", "")  
    ts = ts.replace(".", "")   
    return ts 
def remove_comma(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", "")         
    ts = ts.replace(". ", "")        
    ts = ts.replace(".", "")     
    return ts 

def remove_spaces(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(" ", "")         
    ts = ts.replace("  ", "")        
    ts = ts.replace("   ", "")     
    return ts
def fix_timestamp_format(ts):
    if pd.isna(ts):
        return ts
    
    ts = str(ts).replace(" ", "")  
    
    if len(ts) >= 15:  # es. 27/04/202121:27
        return ts[:10] + ' ' + ts[10:]
    else:
        return ts
def fix_soc (ts):
    if ts > 100.0:
        return ts / 10
    else:
        return ts
def fix_odo(ts):
    if pd.isna(ts):
        return ts
    try:
        ts_str = str(int(ts))
        if len(ts_str) <= 5:
            return int(ts_str) 
        return float(ts_str[:5] + '.' + ts_str[5:])
    except:
        return ts
def fix_vin (ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts)
    if ts.startswith('-8.9'):
        return '1.0'
    elif ts.startswith('-2.4'):
        return '2.0'
    elif ts.startswith('·2.4'):
        return '2.0'
    else:
        return ts

#### Fixing marks

In [398]:
data['odo'] = data['odo'].apply(remove_comma_odo)
data['end_odo'] = data['end_odo'].apply(remove_comma_odo)
data['soc'] = data['soc'].apply(substitute_comma)
data['end_soc'] = data['end_soc'].apply(substitute_comma)

In [399]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,·2.47174E+18,17/07/202116:46,17/07/202119:26,2306385938,2315879688,541.0,352.0,trip,NaN
1,·2.47174E+l8,17/07/202119:29,17/07/202120:01,2315879688,2315879688,NaN,647.0,charge,NaN
2,-2.47174E+18,17/07/202120:01,17/07/202122:36,2315879688,232423125,647.0,478.0,trip,NaN
3,·2.47174E+l8,17/07/202123:05,17/07/2021 23:55,232423125,232723125,474.0,419.0,trip,NaN
4,·2.47174E+18,17/07/2021 23:55,18/07/202101:05,232723125,2327264063,419.0,392.0,trip,NaN

In [400]:
cols_to_float = ['odo', 'end_odo', 'soc', 'end_soc']
for col in cols_to_float:
    data[col] = pd.to_numeric(data[col], errors='coerce')

#### Fixing timestamp format

In [401]:
data['timestamp'] = data['timestamp'].apply(fix_timestamp_format)
data['end_time'] = data['end_time'].apply(fix_timestamp_format) 
data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce', dayfirst=True)
data['end_time'] = pd.to_datetime(data['end_time'], errors='coerce', dayfirst=True)

In [402]:
data['soc'] = data['soc'].apply(fix_soc)
data['end_soc'] = data['end_soc'].apply(fix_soc)
data['odo'] = data['odo'].apply(fix_odo)
data['end_odo'] = data['end_odo'].apply(fix_odo) #it's ok for odo <= 99999

In [403]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,·2.47174E+18,2021-07-17 16:46:00,2021-07-17 19:26:00,23063.85938,23158.79688,54.1,35.2,trip,NaN
1,·2.47174E+l8,2021-07-17 19:29:00,2021-07-17 20:01:00,23158.79688,23158.79688,NaN,64.7,charge,NaN
2,-2.47174E+18,2021-07-17 20:01:00,2021-07-17 22:36:00,23158.79688,23242.31250,64.7,47.8,trip,NaN
3,·2.47174E+l8,2021-07-17 23:05:00,2021-07-17 23:55:00,23242.31250,23272.31250,47.4,41.9,trip,NaN
4,·2.47174E+18,2021-07-17 23:55:00,2021-07-18 01:05:00,23272.31250,23272.64063,41.9,39.2,trip,NaN

In [404]:
cols_to_convert = ['event']
for col in cols_to_convert:
    data[col] = data[col].astype('category')

data['charge_mode'] = data['charge_mode'].apply(remove_spaces)

data['charge_mode'] = data['charge_mode'].replace('', '0')
data['charge_mode'] = data['charge_mode'].fillna('0')
data['charge_mode'] = data['charge_mode'].replace('240.0', '240')
data['charge_mode'] = data['charge_mode'].replace('120.0', '120')
data['charge_mode'] = data['charge_mode'].astype('category')
if '0' not in data['charge_mode'].cat.categories:
    data['charge_mode'] = data['charge_mode'].cat.add_categories('0')
data['vin'] = data['vin'].apply(fix_vin)
data['vin'] = data['vin'].astype('float64')

In [405]:
def original_vin (ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts)
    if ts.startswith('1.0'):
        return '-8.99632E+18'
    elif ts.startswith('2.0'):
        return '-2.47174E+18'
    else:
        return ts

In [406]:
data_to_csv = data.copy()
data_to_csv['vin'] = data_to_csv['vin'].apply(original_vin)

In [407]:
data_to_csv.to_csv('./Dataset_dumarey/original_csv/tmp_cleaned.csv', index=False)

In [408]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vin          32 non-null     float64
 1   timestamp    32 non-null     datetime64[ns]
 2   end_time     32 non-null     datetime64[ns]
 3   odo          32 non-null     float64
 4   end_odo      32 non-null     float64
 5   soc          30 non-null     float64
 6   end_soc      31 non-null     float64
 7   event        32 non-null     category
 8   charge_mode  32 non-null     category
dtypes: category(2), datetime64[ns](2), float64(5)
memory usage: 2.2 KB

In [409]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,2.0,2021-07-17 16:46:00,2021-07-17 19:26:00,23063.85938,23158.79688,54.1,35.2,trip,0
1,2.0,2021-07-17 19:29:00,2021-07-17 20:01:00,23158.79688,23158.79688,NaN,64.7,charge,0
2,2.0,2021-07-17 20:01:00,2021-07-17 22:36:00,23158.79688,23242.31250,64.7,47.8,trip,0
3,2.0,2021-07-17 23:05:00,2021-07-17 23:55:00,23242.31250,23272.31250,47.4,41.9,trip,0
4,2.0,2021-07-17 23:55:00,2021-07-18 01:05:00,23272.31250,23272.64063,41.9,39.2,trip,0