In [1]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split


import pandas as pd
import numpy as np

# Dataset overview

In [2]:
data = pd.read_csv('./Dataset_dumarey/original_csv/tmp.csv')

In [3]:
data.head()

,vin,timestamp,end_time,duration,odo,end_odo,soc,end_soc,event,charge_mode
0,-1.123130e+18,01/01/202100:45,01/01/202100:48,Odays00:03:12,172562.9688,172562.9688,20.3,20,charge,NaN
1,-1.123130e+18,01/01/202100:48,01/01/202100:55,Odays00:07:02,172562.9688,172570.4688,20,17.6,trip,NaN
2,-1.123130e+18,01/01/202100:55,01/01/202101:01,0days00:05:31,172570.4688,172570.5156,17.6,17.2,trip,NaN
3,-1.123130e+18,01/01/202101:01,01/01/202101:03,0days00:01:50,172570.5156,172571.4375,17.2,16.8,trip,NaN
4,-1.123130e+18,01/01/202101:04,01/01/202101:20,Odays00:16:21,172571.4375,172589.2344,16.8,9,trip,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vin          96 non-null     float64
 1   timestamp    96 non-null     object
 2   end_time     96 non-null     object
 3   duration     96 non-null     object
 4   odo          96 non-null     object
 5   end_odo      96 non-null     object
 6   soc          93 non-null     object
 7   end_soc      95 non-null     object
 8   event        96 non-null     object
 9   charge_mode  23 non-null     object
dtypes: float64(1), object(9)
memory usage: 7.6+ KB

# Data Cleaning

In [5]:
def substitute_comma(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", ".")     
    ts = ts.replace(", ", ".")
    ts = ts.replace(" , ", ".")    
    ts = ts.replace(" ,", ".")       
    ts = ts.replace(". ", ".")    
    ts = ts.replace(" .", ".") 
    ts = ts.replace(" . ", ".")       
    return ts 
def remove_comma_odo(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", "")         
    ts = ts.replace(", ", "")        
    ts = ts.replace(" ,", "")  
    ts = ts.replace(".", "")   
    return ts 
def remove_comma(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", "")         
    ts = ts.replace(". ", "")        
    ts = ts.replace(".", "")     
    return ts 

def remove_spaces(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(" ", "")         
    ts = ts.replace("  ", "")        
    ts = ts.replace("   ", "")     
    return ts
def fix_timestamp_format(ts):
    if pd.isna(ts):
        return ts
    
    ts = str(ts).replace(" ", "")  
    
    if len(ts) >= 15:  # es. 27/04/202121:27
        return ts[:10] + ' ' + ts[10:]
    else:
        return ts
def fix_soc (ts):
    if ts > 100.0:
        return ts / 10
    else:
        return ts
def fix_odo(ts):
    if pd.isna(ts):
        return ts
    try:
        ts_str = str(int(ts))
        if len(ts_str) <= 6:
            return int(ts_str) 
        return float(ts_str[:6] + '.' + ts_str[6:])
    except:
        return ts
def fix_vin (ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts)
    if ts.startswith('-8.9'):
        return '1.0'
    elif ts.startswith('-2.4'):
        return '2.0'
    elif ts.startswith('·2.4'):
        return '2.0'
    elif ts.startswith('-1.1'):
        return '3.0'
    else:
        return ts

#### Fixing marks

In [6]:
data['odo'] = data['odo'].apply(remove_comma_odo)
data['end_odo'] = data['end_odo'].apply(remove_comma_odo)
data['soc'] = data['soc'].apply(substitute_comma)
data['end_soc'] = data['end_soc'].apply(substitute_comma)

In [7]:
data.head()

,vin,timestamp,end_time,duration,odo,end_odo,soc,end_soc,event,charge_mode
0,-1.123130e+18,01/01/202100:45,01/01/202100:48,Odays00:03:12,1725629688,1725629688,20.3,20,charge,NaN
1,-1.123130e+18,01/01/202100:48,01/01/202100:55,Odays00:07:02,1725629688,1725704688,20,17.6,trip,NaN
2,-1.123130e+18,01/01/202100:55,01/01/202101:01,0days00:05:31,1725704688,1725705156,17.6,17.2,trip,NaN
3,-1.123130e+18,01/01/202101:01,01/01/202101:03,0days00:01:50,1725705156,1725714375,17.2,16.8,trip,NaN
4,-1.123130e+18,01/01/202101:04,01/01/202101:20,Odays00:16:21,1725714375,1725892344,16.8,9,trip,NaN

In [8]:
#if column 'duration' exists, remove it
if 'duration' in data.columns:
    data = data.drop(columns=['duration'])

In [9]:
cols_to_float = ['odo', 'end_odo', 'soc', 'end_soc']
for col in cols_to_float:
    data[col] = pd.to_numeric(data[col], errors='coerce')

#### Fixing timestamp format

In [10]:
data['timestamp'] = data['timestamp'].apply(fix_timestamp_format)
data['end_time'] = data['end_time'].apply(fix_timestamp_format) 
data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce', dayfirst=True)
data['end_time'] = pd.to_datetime(data['end_time'], errors='coerce', dayfirst=True)

In [11]:
data['soc'] = data['soc'].apply(fix_soc)
data['end_soc'] = data['end_soc'].apply(fix_soc)
data['odo'] = data['odo'].apply(fix_odo)
data['end_odo'] = data['end_odo'].apply(fix_odo) #it's ok for odo <= 99999

In [12]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,-1.123130e+18,2021-01-01 00:45:00,2021-01-01 00:48:00,172562.9688,172562.9688,20.3,20.0,charge,NaN
1,-1.123130e+18,2021-01-01 00:48:00,2021-01-01 00:55:00,172562.9688,172570.4688,20.0,17.6,trip,NaN
2,-1.123130e+18,2021-01-01 00:55:00,2021-01-01 01:01:00,172570.4688,172570.5156,17.6,17.2,trip,NaN
3,-1.123130e+18,2021-01-01 01:01:00,2021-01-01 01:03:00,172570.5156,172571.4375,17.2,16.8,trip,NaN
4,-1.123130e+18,2021-01-01 01:04:00,2021-01-01 01:20:00,172571.4375,172589.2344,16.8,9.0,trip,NaN

In [13]:
cols_to_convert = ['event']
for col in cols_to_convert:
    data[col] = data[col].astype('category')

data['charge_mode'] = data['charge_mode'].apply(remove_spaces)

data['charge_mode'] = data['charge_mode'].replace('', '0')
data['charge_mode'] = data['charge_mode'].fillna('0')
data['charge_mode'] = data['charge_mode'].replace('240.0', '240')
data['charge_mode'] = data['charge_mode'].replace('120.0', '120')
data['charge_mode'] = data['charge_mode'].astype('category')
if '0' not in data['charge_mode'].cat.categories:
    data['charge_mode'] = data['charge_mode'].cat.add_categories('0')
data['vin'] = data['vin'].apply(fix_vin)
data['vin'] = data['vin'].astype('float64')

In [14]:
def original_vin (ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts)
    if ts.startswith('1.0'):
        return '-8.99632E+18'
    elif ts.startswith('2.0'):
        return '-2.47174E+18'
    elif ts.startswith('3.0'):
        return '-1.12313E+18'
    else:
        return ts

In [15]:
data_to_csv = data.copy()
data_to_csv['vin'] = data_to_csv['vin'].apply(original_vin)

In [16]:
data_to_csv.to_csv('./Dataset_dumarey/original_csv/tmp_cleaned.csv', index=False)

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vin          96 non-null     float64
 1   timestamp    96 non-null     datetime64[ns]
 2   end_time     96 non-null     datetime64[ns]
 3   odo          96 non-null     float64
 4   end_odo      96 non-null     float64
 5   soc          92 non-null     float64
 6   end_soc      94 non-null     float64
 7   event        96 non-null     category
 8   charge_mode  96 non-null     category
dtypes: category(2), datetime64[ns](2), float64(5)
memory usage: 5.8 KB

In [18]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,3.0,2021-01-01 00:45:00,2021-01-01 00:48:00,172562.9688,172562.9688,20.3,20.0,charge,0
1,3.0,2021-01-01 00:48:00,2021-01-01 00:55:00,172562.9688,172570.4688,20.0,17.6,trip,0
2,3.0,2021-01-01 00:55:00,2021-01-01 01:01:00,172570.4688,172570.5156,17.6,17.2,trip,0
3,3.0,2021-01-01 01:01:00,2021-01-01 01:03:00,172570.5156,172571.4375,17.2,16.8,trip,0
4,3.0,2021-01-01 01:04:00,2021-01-01 01:20:00,172571.4375,172589.2344,16.8,9.0,trip,0