In [98]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn import tree

import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.pipeline import Pipeline
import torch.nn as nn
from mpl_toolkits.mplot3d import Axes3D  
import plotly.graph_objects as go
from scipy.stats import gaussian_kde
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
from matplotlib import pyplot as plt
from scipy import stats
from plotly.subplots import make_subplots
import plotly.express as px
import plotly.colors as pc
from sklearn.ensemble import IsolationForest

# Dataset overview

In [99]:
data = pd.read_csv('./Dataset_dumarey/original_csv/tmp.csv')

In [100]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,·2.47174E+18,28/05/202112:33,28/05/202118:56,"8,782,421,875","8,963,484,375",584.0,247,trip,NaN
1,·2.47174E+l8,28/05/202119:13,28/05/202119:18,"8,963,484,375","896,578,125",243.0,231,trip,NaN
2,·2.47174E+18,28/05/202119:37,28/05/202119:51,"896,578,125","8,971,859,375",231.0,223,trip,NaN
3,·2.47174E+l8,28/05/202119:52,28/05/2021 20:10,"8,971,859,375","8,971,859,375",223.0,223,charge,NaN
4,·2.47174E+18,28/05/2021 20:10,28/05/2021 21:23,"8,971,859,375","9,006,984,375",223.0,168,trip,NaN

In [101]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vin          32 non-null     object
 1   timestamp    32 non-null     object
 2   end_time     32 non-null     object
 3   odo          32 non-null     object
 4   end_odo      32 non-null     object
 5   soc          30 non-null     float64
 6   end_soc      32 non-null     int64
 7   event        32 non-null     object
 8   charge_mode  10 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 2.4+ KB

# Data Cleaning

In [102]:
def substitute_comma(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", ".")     
    ts = ts.replace(", ", ".")
    ts = ts.replace(" , ", ".")    
    ts = ts.replace(" ,", ".")       
    ts = ts.replace(". ", ".")    
    ts = ts.replace(" .", ".") 
    ts = ts.replace(" . ", ".")       
    return ts 
def remove_comma_odo(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", "")         
    ts = ts.replace(", ", "")        
    ts = ts.replace(" ,", "")  
    ts = ts.replace(".", "")   
    return ts 
def remove_comma(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(",", "")         
    ts = ts.replace(". ", "")        
    ts = ts.replace(".", "")     
    return ts 

def remove_spaces(ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts).strip()
    ts = ts.replace(" ", "")         
    ts = ts.replace("  ", "")        
    ts = ts.replace("   ", "")     
    return ts
def fix_timestamp_format(ts):
    if pd.isna(ts):
        return ts
    
    ts = str(ts).replace(" ", "")  
    
    if len(ts) >= 15:  # es. 27/04/202121:27
        return ts[:10] + ' ' + ts[10:]
    else:
        return ts
def fix_soc (ts):
    if ts > 100.0:
        return ts / 10
    else:
        return ts
def fix_odo(ts):
    if pd.isna(ts):
        return ts
    try:
        ts_str = str(int(ts))
        if len(ts_str) <= 4:
            return int(ts_str) 
        return float(ts_str[:4] + '.' + ts_str[4:])
    except:
        return ts
def fix_vin (ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts)
    if ts.startswith('-8.9'):
        return '1.0'
    elif ts.startswith('-2.4'):
        return '2.0'
    elif ts.startswith('·2.4'):
        return '2.0'
    else:
        return ts

#### Fixing marks

In [103]:
data['odo'] = data['odo'].apply(remove_comma_odo)
data['end_odo'] = data['end_odo'].apply(remove_comma_odo)
data['soc'] = data['soc'].apply(substitute_comma)
data['end_soc'] = data['end_soc'].apply(substitute_comma)

In [104]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,·2.47174E+18,28/05/202112:33,28/05/202118:56,8782421875,8963484375,584.0,247,trip,NaN
1,·2.47174E+l8,28/05/202119:13,28/05/202119:18,8963484375,896578125,243.0,231,trip,NaN
2,·2.47174E+18,28/05/202119:37,28/05/202119:51,896578125,8971859375,231.0,223,trip,NaN
3,·2.47174E+l8,28/05/202119:52,28/05/2021 20:10,8971859375,8971859375,223.0,223,charge,NaN
4,·2.47174E+18,28/05/2021 20:10,28/05/2021 21:23,8971859375,9006984375,223.0,168,trip,NaN

In [105]:
cols_to_float = ['odo', 'end_odo', 'soc', 'end_soc']
for col in cols_to_float:
    data[col] = pd.to_numeric(data[col], errors='coerce')

#### Fixing timestamp format

In [106]:
data['timestamp'] = data['timestamp'].apply(fix_timestamp_format)
data['end_time'] = data['end_time'].apply(fix_timestamp_format) 
data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce', dayfirst=True)
data['end_time'] = pd.to_datetime(data['end_time'], errors='coerce', dayfirst=True)

In [107]:
data['soc'] = data['soc'].apply(fix_soc)
data['end_soc'] = data['end_soc'].apply(fix_soc)
data['odo'] = data['odo'].apply(fix_odo)
data['end_odo'] = data['end_odo'].apply(fix_odo) #it's ok for odo <= 99999

In [108]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,·2.47174E+18,2021-05-28 12:33:00,2021-05-28 18:56:00,8782.421875,8963.484375,58.4,24.7,trip,NaN
1,·2.47174E+l8,2021-05-28 19:13:00,2021-05-28 19:18:00,8963.484375,8965.781250,24.3,23.1,trip,NaN
2,·2.47174E+18,2021-05-28 19:37:00,2021-05-28 19:51:00,8965.781250,8971.859375,23.1,22.3,trip,NaN
3,·2.47174E+l8,2021-05-28 19:52:00,2021-05-28 20:10:00,8971.859375,8971.859375,22.3,22.3,charge,NaN
4,·2.47174E+18,2021-05-28 20:10:00,2021-05-28 21:23:00,8971.859375,9006.984375,22.3,16.8,trip,NaN

In [109]:
cols_to_convert = ['event']
for col in cols_to_convert:
    data[col] = data[col].astype('category')

data['charge_mode'] = data['charge_mode'].apply(remove_spaces)

data['charge_mode'] = data['charge_mode'].replace('', '0')
data['charge_mode'] = data['charge_mode'].fillna('0')
data['charge_mode'] = data['charge_mode'].replace('240.0', '240')
data['charge_mode'] = data['charge_mode'].replace('120.0', '120')
data['charge_mode'] = data['charge_mode'].astype('category')
if '0' not in data['charge_mode'].cat.categories:
    data['charge_mode'] = data['charge_mode'].cat.add_categories('0')
data['vin'] = data['vin'].apply(fix_vin)
data['vin'] = data['vin'].astype('float64')

In [110]:
def original_vin (ts):
    if pd.isna(ts):
        return ts 
    ts = str(ts)
    if ts.startswith('1.0'):
        return '-8.99632E+18'
    elif ts.startswith('2.0'):
        return '-2.47174E+18'
    else:
        return ts

In [111]:
data_to_csv = data.copy()
data_to_csv['vin'] = data_to_csv['vin'].apply(original_vin)

In [112]:
data_to_csv.to_csv('./Dataset_dumarey/original_csv/tmp_cleaned.csv', index=False)

In [113]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vin          32 non-null     float64
 1   timestamp    32 non-null     datetime64[ns]
 2   end_time     32 non-null     datetime64[ns]
 3   odo          32 non-null     float64
 4   end_odo      32 non-null     float64
 5   soc          30 non-null     float64
 6   end_soc      32 non-null     float64
 7   event        32 non-null     category
 8   charge_mode  32 non-null     category
dtypes: category(2), datetime64[ns](2), float64(5)
memory usage: 2.3 KB

In [114]:
data.head()

,vin,timestamp,end_time,odo,end_odo,soc,end_soc,event,charge_mode
0,2.0,2021-05-28 12:33:00,2021-05-28 18:56:00,8782.421875,8963.484375,58.4,24.7,trip,0
1,2.0,2021-05-28 19:13:00,2021-05-28 19:18:00,8963.484375,8965.781250,24.3,23.1,trip,0
2,2.0,2021-05-28 19:37:00,2021-05-28 19:51:00,8965.781250,8971.859375,23.1,22.3,trip,0
3,2.0,2021-05-28 19:52:00,2021-05-28 20:10:00,8971.859375,8971.859375,22.3,22.3,charge,0
4,2.0,2021-05-28 20:10:00,2021-05-28 21:23:00,8971.859375,9006.984375,22.3,16.8,trip,0